export interface ICurrenciesData {
  [index: string]:
    | {
        [index: string]: string;
      }
    | {};
}

export const currenciesData: ICurrenciesData = {
  aed: { aed: "د.إ" },
  ars: { ars: "Ar$" },
  aud: { aud: "A$" },
  bch: { bch: "BCH" },
  bdt: { bdt: "৳" },
  bhd: { bhd: "BD" },
  bmd: { bmd: "B$" },
  bnb: { bnb: "BNB" },
  brl: { brl: "R$" },
  btc: { btc: "₿" },
  cad: { cad: "C$" },
  chf: { chf: "CHF" },
  clp: { clp: "CLP" },
  cny: { cny: "元" },
  czk: { czk: "Kč" },
  dkk: { dkk: "kr." },
  dot: { dot: "DOT" },
  eos: { eos: "EOS" },
  eth: { eth: "Ξ" },
  eur: { eur: "€" },
  gbp: { gbp: "£" },
  hkd: { hkd: "HK$" },
  huf: { huf: "Ft" },
  idr: { idr: "Rp" },
  ils: { ils: "₪" },
  inr: { inr: "₹" },
  jpy: { jpy: "¥" },
  krw: { krw: "₩" },
  kwd: { kwd: "د.ك" },
  lkr: { lkr: "රු," },
  ltc: { ltc: "Ł" },
  mmk: {},
  mxn: {},
  myr: {},
  ngn: {},
  nok: {},
  nzd: {},
  php: { php: "₱" },
  pkr: {},
  pln: {},
  rub: { rub: "₽" },
  sar: { sar: "﷼" },
  sek: { sek: "kr" },
  sgd: {},
  thb: {},
  try: {},
  twd: {},
  uah: { uah: "₴" },
  usd: { usd: "$" },
  vef: {},
  vnd: {},
  xag: {},
  xau: {},
  xdr: {},
  xlm: { xlm: "XLM" },
  xrp: { xrp: "XRP" },
  yfi: {},
  zar: {},
  bits: {},
  link: {},
  sats: {},
};
